version: '2'

services:
  # nginx:
  #   container_name: sf4_nginx
  #   image: nginx:latest
  #   ports:
  #     - 8080:80
  #     - 8000:8000
  #   volumes:
  #     - ./timetracker:/var/www/timetracker
  #     - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
  #     - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  #   links:
  #     - php

  php:
    container_name: sf4_php
    build:
      context: ./
      dockerfile: ./Dockerfile  
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - ./apps/skeleton:/var/www/skeleton:cached
      - ./apps/demo:/var/www/demo:cached
    links:
      - mysql

  mysql:
      container_name: sf4_mysql
      image: mysql:5.7.23
      ports:
          - "3306:3306"
      environment:
          - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
          - MYSQL_DATABASE=${DB_DATABASE}
          - MYSQL_USER=${DB_USER}
          - MYSQL_PASSWORD=${DB_PASS}
      env_file:
          - .env
